//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.24 at 07:13:34 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.flydubai.com/HelloSoap")
package com.flydubai.hellosoap;
